name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Find Xcode project
        run: |
          project_dir=$(find . -name "*.xcodeproj" -type d | head -n 1)
          if [ -z "$project_dir" ]; then
            echo "No Xcode project found."
            exit 1
          fi
          echo "Found project: $project_dir"
          echo "project_dir=$project_dir" >> $GITHUB_ENV
      
      - name: Set Default Scheme
        run: |
          cd $(dirname "$project_dir")
          scheme_list=$(xcodebuild -list -json -project $(basename "$project_dir") | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo "default_scheme=$default" >> $GITHUB_ENV
          echo Using default scheme: $default
      
      - name: Build
        env:
          scheme: ${{ env.default_scheme }}
          SRCROOT: ${{ github.workspace }}/PeteBJJCompFeed
        run: |
          cd $(dirname "$project_dir")
          xcodebuild clean build \
            -scheme "$scheme" \
            -project $(basename "$project_dir") \
            -destination 'platform=macOS,arch=arm64' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            MOMC_OUTPUT_DIR="${SRCROOT}" \
            MOMC_INPUT_RELATIVE_PATH="${SRCROOT}" \
            CORE_DATA_MODEL_PATH="${SRCROOT}/CompetitionsCache/CompetitionsStore.xcdatamodeld" \
            BUILD_ROOT="${SRCROOT}/build" \ 
            CONFIGURATION_BUILD_DIR="${SRCROOT}/build" \
            -verbose
            
      - name: Analyze
        env:
          scheme: ${{ env.default_scheme }}
          SRCROOT: ${{ github.workspace }}/PeteBJJCompFeed
        run: |
          cd $(dirname "$project_dir")
          xcodebuild analyze \
            -scheme "$scheme" \
            -project $(basename "$project_dir") \
            -destination 'platform=macOS,arch=arm64' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            MOMC_OUTPUT_DIR="${SRCROOT}" \
            -verbose
